/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VideoClub;

import java.awt.TextArea;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author arouven
 */
public class StaffForm extends javax.swing.JFrame {
    
    /**
     * Creates new form StaffForm
     */
    public StaffForm() {
        initComponents();
        this.setTitle("Staff Form");
        setDefaultCloseOperation (JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        addStaffButton = new javax.swing.JButton();
        displayAllStaffButton = new javax.swing.JButton();
        searchStaffButton = new javax.swing.JButton();
        updateStaffButton = new javax.swing.JButton();
        deleteStaffButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainMenuButton.setText("Main Menu");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Staff Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 24))); // NOI18N

        addStaffButton.setText("Add Staff");
        addStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffButtonActionPerformed(evt);
            }
        });

        displayAllStaffButton.setText("Display all Staff");
        displayAllStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayAllStaffButtonActionPerformed(evt);
            }
        });

        searchStaffButton.setText("Search by Name");
        searchStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStaffButtonActionPerformed(evt);
            }
        });

        updateStaffButton.setText("Update Staff");
        updateStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStaffButtonActionPerformed(evt);
            }
        });

        deleteStaffButton.setText("Delete Staff");
        deleteStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStaffButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addStaffButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayAllStaffButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchStaffButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateStaffButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteStaffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addStaffButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayAllStaffButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchStaffButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateStaffButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteStaffButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(mainMenuButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    private void addStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffButtonActionPerformed
        AddStaffForm addStaff = new AddStaffForm();
        addStaff.setVisible(true);
    }//GEN-LAST:event_addStaffButtonActionPerformed

    private void displayAllStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAllStaffButtonActionPerformed
        TextArea stDetails = new TextArea();
        String outputText = "";
        outputText = MainMenu.stArray.stream().map((st) -> st.displayStaffDetails()).reduce(outputText, String::concat);
        stDetails.setText(outputText);
        JOptionPane.showMessageDialog(this, stDetails, "Staff Detail", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_displayAllStaffButtonActionPerformed

    private void searchStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStaffButtonActionPerformed
        String stNameToSearch = JOptionPane.showInputDialog(this, "Search the staff(name): ", "Staff Name", JOptionPane.INFORMATION_MESSAGE);
        if (stNameToSearch != null) {
            int currentPosition = 0;
            for(Staff st: MainMenu.stArray){
                String stName = st.getStaffName();
                if(stNameToSearch.equals(stName)){
                    TextArea stDetails = new TextArea();
                    stDetails.setText(st.displayStaffDetails());
                    JOptionPane.showMessageDialog(this, stDetails, "Staff Detail", JOptionPane.INFORMATION_MESSAGE);

                    return;
                }
                currentPosition ++;
            }

            System.out.println("current " + currentPosition);
            System.out.println("size " + MainMenu.stArray.size());

            if(currentPosition > MainMenu.stArray.size()-1){
                JOptionPane.showMessageDialog(this, "Staff " + stNameToSearch + " Not Found!", "Not Found", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            System.out.println("cancel is pressed");
        }
    }//GEN-LAST:event_searchStaffButtonActionPerformed

    private void updateStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStaffButtonActionPerformed
        String stNameToSearch = JOptionPane.showInputDialog(this, "Search the staff(name) to update: ", "Staff Name", JOptionPane.INFORMATION_MESSAGE);
        if (stNameToSearch != null) {
            int currentPosition = 0;
            for(Staff st : MainMenu.stArray){
                String stName = st.getStaffName();
                if(stNameToSearch.equals(stName)){
                    UpdateStaffForm updateStaff = new UpdateStaffForm(currentPosition);
                    updateStaff.setVisible(true);
                    System.out.println(currentPosition);
                    return;
                }
                currentPosition ++;
            }
            if(currentPosition > MainMenu.stArray.size()-1){
                JOptionPane.showMessageDialog(this, "Staff " + stNameToSearch + " Not Found!", "Not Found", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            System.out.println("cancel is pressed.");
        }
    }//GEN-LAST:event_updateStaffButtonActionPerformed

    private void deleteStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStaffButtonActionPerformed
        String stNameToSearch = JOptionPane.showInputDialog(this, "Search the staff(name) to delete: ", "Staff Name", JOptionPane.INFORMATION_MESSAGE);
        if (stNameToSearch != null) {
            int currentPosition = 0;
            for(Staff st: MainMenu.stArray){
                String stName = st.getStaffName();
                if(stNameToSearch.equals(stName)){
                    int descision = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this staff: " + stName + " ?","Delete Staff", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

                    if(descision == 0){
                        MainMenu.stArray.remove(currentPosition);
                        System.out.println("deleted");
                        JOptionPane.showMessageDialog(this, stName + " was deleted.", "Staff Deleted", JOptionPane.DEFAULT_OPTION);
                        return;//exit the button function
                    }
                    else{
                        System.out.println("do nothing");
                    }
                    break;
                }
                currentPosition ++;
            }

            System.out.println("current " + currentPosition);
            System.out.println("size " + MainMenu.stArray.size());

            if(currentPosition > MainMenu.stArray.size()-1){
                JOptionPane.showMessageDialog(this, "Staff " + stNameToSearch + " Not Found!", "Not Found", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            System.out.println("cancel is pressed.");
        }
    }//GEN-LAST:event_deleteStaffButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStaffButton;
    private javax.swing.JButton deleteStaffButton;
    private javax.swing.JButton displayAllStaffButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JButton searchStaffButton;
    private javax.swing.JButton updateStaffButton;
    // End of variables declaration//GEN-END:variables
}
